server:
  port: 8082
  servlet:
    context-path: /pagamento

spring:
  application:
    name: pagamento
  datasource:
    url: jdbc:postgresql://localhost:5432/pagamento-service-mq
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 40
      idle-timeout: 10000
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
