server:
  port: 8081
  servlet:
    context-path: /crud

spring:
  application:
    name: crud
  datasource:
    url: jdbc:postgresql://localhost:5432/produtos-service-mq
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 40
      idle-timeout: 10000
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
crud:
  rabbitmq:
    exchange: crud.exchange
    routingKey: crud.produto.routingKey
security:
  jwt:
    token:
      secret-key: chave_microservices